language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install: "pip install pgen2"
script:
  - python -m compileall -f .
  - python -c "from mython.tests.__main__ import *; unittest.main()"
