language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install: "pip install pgen2 --use-mirrors"
script:
  - python -m compileall -f .
  - python -m mython.myparser mython/tests/test_parser_0_0_2.my
notifications:
  irc: "irc.freenode.org#mython"
